services:
  pgp-web-app:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
    volumes:
      - pgp_uploads:/app/uploads
      - pgp_gnupg:/app/gnupg_home
      - pgp_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - pgp-web-app
    restart: unless-stopped
    profiles:
      - production

volumes:
  pgp_uploads:
    driver: local
  pgp_gnupg:
    driver: local
  pgp_logs:
    driver: local
